runtime: python
env: flex

runtime_config:
    python_version: 3

entrypoint: gunicorn --worker-class gevent -b :$PORT main:app --timeout 90

beta_settings:
  cloud_sql_instances: civil-clarity-273515:us-central1:recruit-find-work=tcp:5432